//RECORRER LOS DATOS

// SE ASEGURAN QUE LOS VALORES DE LA IZQUIERDA SEAN LOS VALORES MAS CHICOS Y LOS DE LA DERECHA MAYORES

//PREGUNTAR DE DERECHA A IZQUIERDA, SI SOY EL ELEMENTO MÁS CHICO QUE EL DE COMPARACION.

//SI ESO OCURRE ME INSERTO EN ESA POSICION.