//1.LA FUNCION FLECHA NOS DA UNA SINTAXIS MAS LIMPIA Y FACIL DE LEER//
//2.NORMALMENTE SE ALMACENAN EN CONST O VARIABLES
//3. EM LAS FUNCIONES FLECHA NO EXISTE EL OBJETO "this", ESTAS NO PUEDEN SER PROTOTIPOS

let saludar = () => {
    return "Hola mundo"
};
console.log(saludar());

//3. SHORT ARROW FUNCTIONS
// REGLAS DE SINTAXIS
//*SI MI FUNCION SOLO RETORNA UN VALOR, PUEDO QUITAR EL RETURN EXPLICITO, LAS LLAVES Y HACER USO DEL RETURN IMPLICITO
const suma = (a,b)=> a + b;

console.log(suma(4,9));

//SHORT ARROW FUNCTION CON UN SOLO PARAMETRO
//REGLAS DE SINTAXIS:
//*SI MI FUNCION SOLO RETORNA UN VALOR Y PIDE UN SOLO PARAMETRO PUEDO APLICAR LA REGLA ANTERIOR Y ADEMAS, QUITAR LOS PARENTESIS DEL PARAMETRO

const hola = persona => "Hola" + persona;
console.log(hola(" Erik"));